# Generated by Django 5.2.12 on 2026-06-08 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_partner_gender'),
        ('chat', '0024_alter_scheduledmessage_status'),
        ('qurtoba', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qurtobarecord',
            name='account_task_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Account Task Done At'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='account_task_done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Account Task Done By'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='account_task_state',
            field=models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'تم'), ('canceled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='Account Task State'),
        ),
        migrations.AddIndex(
            model_name='qurtobarecord',
            index=models.Index(fields=['account_task_state', 'type'], name='qr_acct_task_state_idx'),
        ),
    ]
