# Generated by Django 5.2.12 on 2026-05-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qurtobacustomer',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='مديونيات'),
        ),
    ]
