# Generated by Django 5.2.12 on 2026-06-10 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('qurtoba', '0002_qurtobarecord_account_task_done_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QurtobaSyncProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('model_label', models.CharField(blank=True, max_length=120, null=True, verbose_name='Model')),
                ('operation', models.CharField(choices=[('push_record', 'Push Record')], default='push_record', max_length=40, verbose_name='Operation')),
                ('status', models.CharField(choices=[('failed', 'فشل'), ('done', 'تم')], db_index=True, default='failed', max_length=12, verbose_name='Status')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Last Error')),
                ('attempts', models.IntegerField(default=0, verbose_name='Attempts')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Attempt')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('notified', models.BooleanField(default=False, verbose_name='Notified')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Qurtoba Sync Problem',
                'verbose_name_plural': 'Qurtoba Sync Problems',
                'ordering': ['-created_at'],
            },
        ),
    ]
