# Generated by Django 5.2.12 on 2026-05-07 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0002_qurtobacustomer_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qurtobacustomer',
            options={'ordering': ['name'], 'verbose_name': 'Qurtoba Customer', 'verbose_name_plural': 'Qurtoba Customers'},
        ),
        migrations.AlterModelOptions(
            name='qurtobarecord',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Qurtoba Record', 'verbose_name_plural': 'Qurtoba Records'},
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='qurtoba.qurtobacustomer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='qurtobacustomer',
            name='device_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Device No'),
        ),
        migrations.AlterField(
            model_name='qurtobacustomer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='qurtobacustomer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='qurtobacustomer',
            name='qurtoba_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Customer ID (Qurtoba)'),
        ),
        migrations.AlterField(
            model_name='qurtobacustomer',
            name='seller_qurtoba_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Seller ID'),
        ),
        migrations.AlterField(
            model_name='qurtobarecord',
            name='customer_data_qurtoba_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Customer ID (Qurtoba)'),
        ),
        migrations.AlterField(
            model_name='qurtobarecord',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='qurtobarecord',
            name='is_down',
            field=models.BooleanField(default=False, verbose_name='Is Payment'),
        ),
        migrations.AlterField(
            model_name='qurtobarecord',
            name='rest',
            field=models.FloatField(blank=True, null=True, verbose_name='Rest'),
        ),
        migrations.AlterField(
            model_name='qurtobarecord',
            name='seller_qurtoba_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Seller ID (Qurtoba)'),
        ),
        migrations.AlterField(
            model_name='qurtobarecord',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='qurtobarecord',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
    ]
