# Generated by Django 5.2.12 on 2026-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0003_alter_qurtobacustomer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qurtobarecord',
            name='type',
            field=models.CharField(choices=[('كاش', 'كاش'), ('كاش(5)', 'كاش(5)'), ('كاش(10)', 'كاش(10)'), ('كاش(20)', 'كاش(20)'), ('فورى', 'فورى'), ('أمان', 'أمان'), ('طاير', 'طاير'), ('مصاريف خدمه', 'مصاريف خدمه'), ('تحصيل', 'تحصيل'), ('شراء كاش', 'شراء كاش'), ('شراء فورى', 'شراء فورى'), ('مندوب', 'مندوب')], max_length=50, verbose_name='Type'),
        ),
    ]
