# Generated by Django 5.2.12 on 2026-06-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0003_qurtobasyncproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='qurtobapendingpayment',
            name='source_message_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Source Message'),
        ),
    ]
