# Generated by Django 5.2.12 on 2026-06-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0004_qurtobapendingpayment_source_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qurtobasyncproblem',
            name='payload',
            field=models.TextField(blank=True, null=True, verbose_name='Payload'),
        ),
    ]
