# Generated by Django 5.2.12 on 2026-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0005_qurtobacustomeraccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qurtobarecord',
            name='qurtoba_posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Posted at'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='qurtoba_record_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qurtoba Record ID'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='qurtoba_sync_error',
            field=models.TextField(blank=True, null=True, verbose_name='Sync Error'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='qurtoba_synced',
            field=models.BooleanField(default=False, verbose_name='Posted to Qurtoba'),
        ),
    ]
