# Generated by Django 5.2.12 on 2026-05-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_attachment_metadata_alter_attachment_created_at'),
        ('qurtoba', '0006_qurtobarecord_qurtoba_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_device',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_done',
            field=models.BooleanField(default=False, verbose_name='Cash-SYS Done'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cash Done At'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_fee',
            field=models.FloatField(blank=True, null=True, verbose_name='Cash-SYS Fee'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_sim',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SIM Number'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qurtoba_records', to='base.partner', verbose_name='Partner'),
        ),
    ]
