# Generated by Django 5.2.14 on 2026-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0006_qurtobarecord_cash_sys_sim_code_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qurtobasyncproblem',
            name='operation',
            field=models.CharField(choices=[('push_record', 'Push Record'), ('cash_sys_order', 'Cash-SYS Order'), ('cash_sys_order_progress', 'Cash-SYS Order Progress'), ('cash_sys_order_done', 'Cash-SYS Order Done'), ('cash_sys_order_canceled', 'Cash-SYS Order Canceled')], default='push_record', max_length=40, verbose_name='Operation'),
        ),
    ]
