# Generated by Django 5.2.12 on 2026-09-26 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0008_alter_qurtobarecord_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QurtobaGroupLinkWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجروب')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='qurtoba.qurtobacustomer', verbose_name='عميل قرطبة')),
            ],
            options={
                'verbose_name': 'ربط الجروب بعميل قرطبة',
                'abstract': False,
            },
        ),
    ]
