# Generated by Django 5.2.12 on 2026-05-31 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_partner_gender'),
        ('qurtoba', '0008_cashsysplan_cashsysvippage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QurtobaPendingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('conversation_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(choices=[('شراء كاش', 'شراء كاش'), ('شراء فورى', 'شراء فورى')], max_length=20, verbose_name='Type')),
                ('value', models.FloatField(verbose_name='Amount')),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer_confirmation_text', models.TextField(verbose_name='Customer Confirmation')),
                ('reason', models.CharField(choices=[('payment_review', 'سداد بانتظار المراجعة')], default='payment_review', max_length=40)),
                ('review_state', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('denied', 'مرفوض')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('created_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qurtoba.qurtobarecord', verbose_name='Created Record')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payments', to='qurtoba.qurtobacustomer', verbose_name='Customer')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qurtoba_pending_payments', to='base.partner', verbose_name='Chat Partner')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('screenshot_attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.attachment', verbose_name='Screenshot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Pending Qurtoba Payment',
                'verbose_name_plural': 'Pending Qurtoba Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QurtobaPendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('conversation_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(choices=[('كاش', 'كاش'), ('كاش(5)', 'كاش(5)'), ('كاش(10)', 'كاش(10)'), ('كاش(20)', 'كاش(20)'), ('فورى', 'فورى'), ('أمان', 'أمان'), ('طاير', 'طاير'), ('مصاريف خدمه', 'مصاريف خدمه')], max_length=50, verbose_name='Type')),
                ('value', models.FloatField(verbose_name='Amount')),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('grade_limit_exceeded', 'تجاوز الحد الائتماني')], default='grade_limit_exceeded', max_length=40)),
                ('review_state', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('denied', 'مرفوض')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('created_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qurtoba.qurtobarecord', verbose_name='Created Record')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transactions', to='qurtoba.qurtobacustomer', verbose_name='Customer')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qurtoba_pending_transactions', to='base.partner', verbose_name='Chat Partner')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Pending Qurtoba Transaction',
                'verbose_name_plural': 'Pending Qurtoba Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
