# Generated by Django 5.2.12 on 2026-06-01 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_partner_gender'),
        ('chat', '0024_alter_scheduledmessage_status'),
        ('qurtoba', '0009_qurtobapendingpayment_qurtobapendingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='qurtobarecord',
            name='origin_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qurtoba_records', to='chat.message', verbose_name='Source Message'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='receipt_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.attachment', verbose_name='Receipt Image'),
        ),
    ]
