# Generated by Django 5.2.12 on 2026-06-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0010_qurtobarecord_origin_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_canceled_reason',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cancel Reason'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_event_log',
            field=models.JSONField(blank=True, default=list, verbose_name='Processed Events'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_fulfilled',
            field=models.FloatField(blank=True, null=True, verbose_name='Fulfilled Amount'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_original_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Original Value (pre-reroute)'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_reroute_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Reroute Amount (awaiting new number)'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('done', 'Done'), ('canceled', 'Canceled'), ('rerouted', 'Rerouted')], db_index=True, default='pending', max_length=20, verbose_name='Cash-SYS State'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_transactions',
            field=models.JSONField(blank=True, null=True, verbose_name='Cash-SYS Transfers'),
        ),
        migrations.AddField(
            model_name='qurtobarecord',
            name='root_external_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Root External Ref'),
        ),
    ]
