# Generated by Django 5.2.12 on 2026-06-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0011_qurtobarecord_cash_sys_canceled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qurtobapendingtransaction',
            name='source_message_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Source Message'),
        ),
    ]
