# Generated by Django 5.2.12 on 2026-06-02 13:35

import django.db.models.deletion
import modules.base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_partner_gender'),
        ('qurtoba', '0012_qurtobapendingtransaction_source_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qurtobapendingpayment',
            name='screenshot_attachment',
            field=modules.base.fields.AttachmentForeignKeyField(allowed_types=['image'], blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.attachment', upload_to='qurtoba/payment_screenshots', verbose_name='Screenshot'),
        ),
    ]
