# Generated by Django 5.2.12 on 2026-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurtoba', '0013_alter_qurtobapendingpayment_screenshot_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='qurtobarecord',
            name='cash_sys_service_fee_done',
            field=models.BooleanField(default=False, verbose_name='Service Fee Processed'),
        ),
    ]
